In [47]:
import pandas as pd 

# Data Processing

df = pd.DataFrame({
    'Name' : ['Ram','Shyam','Om','Sita','Gita'],
    'Age' : [23,None,44,23,None],
    'Salary' : [50000,60000,70000,None,None]
})
df

print(df.isnull().mean() * 100)

Name       0.0
Age       40.0
Salary    40.0
dtype: float64

In [48]:
df.isna().sum()

Name      0
Age       2
Salary    2
dtype: int64

In [49]:
df.dropna()

  Name   Age   Salary
0  Ram  23.0  50000.0
2   Om  44.0  70000.0

In [51]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].mean(),inplace=True)
df

C:\Users\Acer\AppData\Local\Temp\ipykernel_8568\4170140246.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
C:\Users\Acer\AppData\Local\Temp\ipykernel_8568\4170140246.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)

    Name   Age   Salary
0    Ram  23.0  50000.0
1  Shyam  30.0  60000.0
2     Om  44.0  70000.0
3   Sita  23.0  60000.0
4   Gita  30.0  60000.0

Label Encoding