In [31]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd 

df = pd.read_csv('students.csv')
df_label = df.copy()
df_label

le = LabelEncoder()
df_label['Sex_Encoded'] = le.fit_transform(df_label['sex'])
df_label['Major_Encoded'] = le.fit_transform(df_label['major'])

df_label[['case','sex','Sex_Encoded','height','weight','major','Major_Encoded']].head(5)

,case,sex,Sex_Encoded,height,weight,major,Major_Encoded
0,1,Female,0,172,63,Business,0
1,2,Female,0,170,70,International Affairs,2
2,3,Female,0,170,52,Other,3
3,4,Female,0,171,52,Communications,1
4,5,Male,1,186,90,Business,0

one hot encoding

In [33]:
df_encoded = pd.get_dummies(df_label, columns=['major'], dtype=int ).head(10)
df_encoded

,case,sex,height,weight,Sex_Encoded,Major_Encoded,major_Business,major_Communications,major_International Affairs,major_Other
0,1,Female,172,63,0,0,1,0,0,0
1,2,Female,170,70,0,2,0,0,1,0
2,3,Female,170,52,0,3,0,0,0,1
3,4,Female,171,52,0,1,0,1,0,0
4,5,Male,186,90,1,0,1,0,0,0
5,6,Male,183,79,1,0,1,0,0,0
6,7,Male,170,66,1,1,0,1,0,0
7,8,Female,169,56,0,0,1,0,0,0
8,9,Male,175,75,1,2,0,0,1,0
9,10,Female,175,65,0,1,0,1,0,0

In [ ]:
# Feature Scaling

In [67]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd

data = pd.DataFrame({
    "studyhrs":[1,2,3,4,5],
    "testscore":[40,50,60,70,80]
})

# Standard Scaling
scaler = StandardScaler()

scaled = scaler.fit_transform(data)

scaled_df = pd.DataFrame(
    scaled,
    columns=['studyhrs', 'testscore']
)

print("Standard Scaled Data")
print(scaled_df)

# MinMax Scaling
min_max_scaler = MinMaxScaler()

min_max_scaled = min_max_scaler.fit_transform(data)

min_max_scaled_df = pd.DataFrame(
    min_max_scaled,
    columns=['studyhrs', 'testscore']
)

print("\nMinMax Scaled Data")
print(min_max_scaled_df)

x = data[['studyhrs']]
y=data[['testscore']]

X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=42)
print("Training data")
print(X_train)

print("Test Data")
print(X_test)

print("Training data")
print(Y_train)

print("Test Data")
print(Y_test)

Standard Scaled Data
   studyhrs  testscore
0 -1.414214  -1.414214
1 -0.707107  -0.707107
2  0.000000   0.000000
3  0.707107   0.707107
4  1.414214   1.414214

MinMax Scaled Data
   studyhrs  testscore
0      0.00       0.00
1      0.25       0.25
2      0.50       0.50
3      0.75       0.75
4      1.00       1.00
Training data
   studyhrs
4         5
2         3
0         1
3         4
Test Data
   studyhrs
1         2
Training data
   testscore
4         80
2         60
0         40
3         70
Test Data
   testscore
1         50