In [60]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv("beginner_ml_project_dataset.csv")
df

# label encoding

df_l = df.copy()
# le = LabelEncoder()
# df_l['gender_encode'] = le.fit_transform(df_l['Gender'])
# df_l['pass_encode'] = le.fit_transform(df_l['Passed'])
# df_l



le=LabelEncoder()
df_l['gender_encode'] =le.fit_transform(df_l['Gender'])
df_l['pass_encode'] =le.fit_transform(df_l['Passed'])
df_l

# one hot encode
# df_encode = pd.get_dummies(df_l, columns=['City'])
# df_encode

# pd.get_dummies(df_l,columns=['Passed'],dtype=int)

df_encode=pd.get_dummies(df_l, columns=['Name'])
df_encode


# feature scaling



df=pd.DataFrame({
    'study' : [1,2,3,4],
    'score' : [20,30,40,50]
    
})
df

scaler=StandardScaler()
scaled = scaler.fit_transform(df)
scaled_encode = pd.DataFrame(scaled, columns=['study','score'])
scaled_encode

mscaler = MinMaxScaler()
mscaled=mscaler.fit_transform(df)
msencode=pd.DataFrame(mscaled,columns=['study','score'])
msencode

# splitdata

x=df[['study']]
y=df[['score']]

x_Train,x_Test,y_Train,y_Test = train_test_split(x,y,test_size=0.2,random_state=42)
x_Train

   study
3      4
0      1
2      3

In [37]:
df

     Name  Gender        City Passed
0   Aarav    Male      Butwal    Yes
1    Sita  Female   Kathmandu    Yes
2   Rohan    Male     Pokhara     No
3  Anjali  Female    Lalitpur    Yes
4   Kiran    Male      Butwal     No
5   Priya  Female     Chitwan    Yes
6   Bibek    Male  Biratnagar     No
7   Sneha  Female      Dharan    Yes