In [4]:
import numpy as np 
import seaborn as sns

from scipy.stats import chi2_contingency
import  pandas as pd 

df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

*********** Contingency Table ***************

In [8]:
contingency_table = pd.crosstab(df['sex'],df['survived'])
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [13]:
chi2, p_value, dof , expected = chi2_contingency(contingency_table)
print(expected)
print(p_value)
print(chi2)

[[193.47474747 120.52525253]
 [355.52525253 221.47474747]]
1.1973570627755645e-58
260.71702016732104

In [14]:
alpha = 0.05

if p_value < alpha:
    print("We reject null hypothesis & there's significant relationship between gender and survivor")
else:
    print("There's no connection ")

We reject null hypothesis & there's significant relationship between gender and survivor