In [47]:
import numpy as np 
import pandas as pd

dx = pd.DataFrame([
    ["Nepal", "Federal Democratic Republic of Nepal", "NPR", "Kathmandu", "South Asia", "Asia", 28.3949, 84.1240, 28.7, 30000000, 34.5],
    ["India", "Republic of India", "INR", "New Delhi", "South Asia", "Asia", 20.5937, 78.9629, 60.5, 1400000000, 48.1],
    ["USA", "United States of America", "USD", "Washington D.C.", "North America", "North America", 37.0902, -95.7129, 44.4, 331000000, 50.7],
    ["China", "People's Republic of China", "CNY", "Beijing", "East Asia", "Asia", 35.8617, 104.1954, 56.2, 1440000000, 48.9],
    ["UK", "United Kingdom", "GBP", "London", "Western Europe", "Europe", 55.3781, -3.4360, 71.0, 67000000, 51.5]
], columns=[
    "country",
    "country_long",
    "currency",
    "capital_c",
    "region",
    "continent",
    "latitude",
    "longitude",
    "agricultural_land",
    "population",
    "women_paf"
])

print(dx)

  country                          country_long currency        capital_c  \
0   Nepal  Federal Democratic Republic of Nepal      NPR        Kathmandu
1   India                     Republic of India      INR        New Delhi
2     USA              United States of America      USD  Washington D.C.
3   China            People's Republic of China      CNY          Beijing
4      UK                        United Kingdom      GBP           London

           region      continent  latitude  longitude  agricultural_land  \
0      South Asia           Asia   28.3949    84.1240               28.7
1      South Asia           Asia   20.5937    78.9629               60.5
2   North America  North America   37.0902   -95.7129               44.4
3       East Asia           Asia   35.8617   104.1954               56.2
4  Western Europe         Europe   55.3781    -3.4360               71.0

   population  women_paf
0    30000000       34.5
1  1400000000       48.1
2   331000000       50.7
3  1440000000       48.9
4    67000000       51.5

In [9]:
#some imp commands:
#df.shape,
#df.info() - not null
#df.describe()

        latitude   longitude  agricultural_land    population  women_paf
count   5.000000    5.000000           5.000000  5.000000e+00   5.000000
mean   35.463720   33.626680          52.160000  6.536000e+08  46.740000
std    12.946738   83.198055          16.212742  7.093281e+08   6.976245
min    20.593700  -95.712900          28.700000  3.000000e+07  34.500000
25%    28.394900   -3.436000          44.400000  6.700000e+07  48.100000
50%    35.861700   78.962900          56.200000  3.310000e+08  48.900000
75%    37.090200   84.124000          60.500000  1.400000e+09  50.700000
max    55.378100  104.195400          71.000000  1.440000e+09  51.500000

In [38]:
#df[df['population'] == df['population'].max()]

In [41]:
#df['population'].max()

In [48]:
dx

,country,country_long,currency,capital_c,region,continent,latitude,longitude,agricultural_land,population,women_paf
0,Nepal,Federal Democratic Republic of Nepal,NPR,Kathmandu,South Asia,Asia,28.3949,84.1240,28.7,30000000,34.5
1,India,Republic of India,INR,New Delhi,South Asia,Asia,20.5937,78.9629,60.5,1400000000,48.1
2,USA,United States of America,USD,Washington D.C.,North America,North America,37.0902,-95.7129,44.4,331000000,50.7
3,China,People's Republic of China,CNY,Beijing,East Asia,Asia,35.8617,104.1954,56.2,1440000000,48.9
4,UK,United Kingdom,GBP,London,Western Europe,Europe,55.3781,-3.4360,71.0,67000000,51.5

In [51]:
dx[dx['population'] == dx['population'].max()]['country']

3    China
Name: country, dtype: object

In [53]:
dx[dx['population'] == dx['population'].max()]['capital_c']

3    Beijing
Name: capital_c, dtype: object

In [55]:
dx.columns

Index(['country', 'country_long', 'currency', 'capital_c', 'region',
       'continent', 'latitude', 'longitude', 'agricultural_land', 'population',
       'women_paf'],
      dtype='object')

In [59]:
dx[dx['population']==dx['population'].min()]['country']

0    Nepal
Name: country, dtype: object

In [60]:
dx[dx['population']==dx['population'].min()]['capital_c']

0    Kathmandu
Name: capital_c, dtype: object

In [64]:

dx.head()

,country,country_long,currency,capital_c,region,continent,latitude,longitude,agricultural_land,population,women_paf
0,Nepal,Federal Democratic Republic of Nepal,NPR,Kathmandu,South Asia,Asia,28.3949,84.1240,28.7,30000000,34.5
1,India,Republic of India,INR,New Delhi,South Asia,Asia,20.5937,78.9629,60.5,1400000000,48.1
2,USA,United States of America,USD,Washington D.C.,North America,North America,37.0902,-95.7129,44.4,331000000,50.7
3,China,People's Republic of China,CNY,Beijing,East Asia,Asia,35.8617,104.1954,56.2,1440000000,48.9
4,UK,United Kingdom,GBP,London,Western Europe,Europe,55.3781,-3.4360,71.0,67000000,51.5

In [69]:
#for sorting 
dx.sort_values(by = 'longitude',ascending=False, inplace=True)
dx['country'].head()

3    China
0    Nepal
1    India
4       UK
2      USA
Name: country, dtype: object

In [85]:
dx['region'].value_counts().count()

np.int64(4)

In [101]:
dx['region'].value_counts()['East Asia']

np.int64(1)

In [104]:
dx[dx['region'] == 'South Asia']['country']

0    Nepal
1    India
Name: country, dtype: object

In [121]:
dx[dx['population']  == dx['population'].nlargest(2).iloc[1]]['currency']

1    INR
Name: currency, dtype: object

In [122]:
dx.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 3 to 2
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            5 non-null      object
 1   country_long       5 non-null      object
 2   currency           5 non-null      object
 3   capital_c          5 non-null      object
 4   region             5 non-null      object
 5   continent          5 non-null      object
 6   latitude           5 non-null      float64
 7   longitude          5 non-null      float64
 8   agricultural_land  5 non-null      float64
 9   population         5 non-null      int64
 10  women_paf          5 non-null      float64
dtypes: float64(4), int64(1), object(6)
memory usage: 652.0+ bytes

In [123]:
dx.head()

,country,country_long,currency,capital_c,region,continent,latitude,longitude,agricultural_land,population,women_paf
3,China,People's Republic of China,CNY,Beijing,East Asia,Asia,35.8617,104.1954,56.2,1440000000,48.9
0,Nepal,Federal Democratic Republic of Nepal,NPR,Kathmandu,South Asia,Asia,28.3949,84.1240,28.7,30000000,34.5
1,India,Republic of India,INR,New Delhi,South Asia,Asia,20.5937,78.9629,60.5,1400000000,48.1
4,UK,United Kingdom,GBP,London,Western Europe,Europe,55.3781,-3.4360,71.0,67000000,51.5
2,USA,United States of America,USD,Washington D.C.,North America,North America,37.0902,-95.7129,44.4,331000000,50.7

In [126]:
dx[dx['women_paf'].isna()]['country']

Series([], Name: country, dtype: object)

In [175]:
count = 0
def counting(txt):
    global count
    if 'Republic' in txt:
        count += 1
    return txt
dx['country_long'].apply(counting)
print(count)

3

In [182]:
dx[dx['continent'] == "Asia"]['population'].max()

1440000000

In [180]:
asia_reg = dx[dx['continent'] == "Asia"]
asia_reg

,country,country_long,currency,capital_c,region,continent,latitude,longitude,agricultural_land,population,women_paf
3,China,People's Republic of China,CNY,Beijing,East Asia,Asia,35.8617,104.1954,56.2,1440000000,48.9
0,Nepal,Federal Democratic Republic of Nepal,NPR,Kathmandu,South Asia,Asia,28.3949,84.1240,28.7,30000000,34.5
1,India,Republic of India,INR,New Delhi,South Asia,Asia,20.5937,78.9629,60.5,1400000000,48.1

In [186]:
asia = dx[dx['continent'] == 'Asia']
asia

,country,country_long,currency,capital_c,region,continent,latitude,longitude,agricultural_land,population,women_paf
3,China,People's Republic of China,CNY,Beijing,East Asia,Asia,35.8617,104.1954,56.2,1440000000,48.9
0,Nepal,Federal Democratic Republic of Nepal,NPR,Kathmandu,South Asia,Asia,28.3949,84.1240,28.7,30000000,34.5
1,India,Republic of India,INR,New Delhi,South Asia,Asia,20.5937,78.9629,60.5,1400000000,48.1

In [196]:
asia[asia['population'] == asia['population'].max()]['country']

3    China
Name: country, dtype: object